config/routes.rb
Rails.application.routes.draw do
  resources :payments, only: [:create]
  
  resources :charges
  
  resources :profiles, only: [:show]
  
  resources :goals do
    patch 'achieve', on: :member  #achieve_goal_path(goal)
  end

  resources :goal_comments do
    resources :likes 
  end  
  resources :blogs  
  
  
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :registrations => "registrations" }
  
  root 'pages#getintouch'
  get '/confirmation' => 'pages#confirmation'
  
  get '/get-in-touch' => 'pages#getintouch'
  
  get 'thank-you' => 'pages#thank_you'
  post 'thank-you' => 'pages#thank_you'
  
  get 'purchase' => 'pages#purchase'
  post 'purchase' => 'payments#create'
  
  get 'about' => 'pages#about'

  get 'faq' => 'pages#faq'

  get 'contact' => 'pages#contact'
  post 'contact' => 'pages#contact'

  get 'form_input', to: 'form_example#form_input'

  post 'form_output', to: 'form_example#form_output'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)
    can :manage, User, id: user.id
    if user.is_admin?
        can :access, :rails_admin
        can :dashboard
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
	validates :creator, presence: true
	validates :creator, length: {minimum:5}
	validates :title, presence: true
	validates :title, length: {maximum:200}
	validates :body, length: {minimum:50}
	has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog
end

app/models/goal.rb
class Goal < ActiveRecord::Base
    
    belongs_to :user
    has_many :goal_comments, dependent: :destroy
    has_many :likes, as: :likeable
end

app/models/goal_comment.rb
class GoalComment < ActiveRecord::Base
    belongs_to :goal
    belongs_to :user
    
    has_many :likes, as: :likeable
end

app/models/like.rb
class Like < ActiveRecord::Base
    
   belongs_to :likeable, polymorphic: true #How to get dependent: :destroy here? 
end

app/models/streak.rb
class Streak < ActiveRecord::Base
  
  belongs_to :User, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  has_many :goals, dependent: :destroy
  has_many :goal_comments, dependent: :destroy
  # has_one :streak, dependent: :destroy  # use a streak model if you want to maintain a history of streak over times
  
  
  # This method calculates data on the fly (meaning it's not stored in the database)
  def streak
    result = 0
    goals.order(created_at: :desc).each do |goal|
      # TODO ignore new goals in the streak 
      if goal.achieved_status?
        result += 1 
      elsif result == 0
        # ignore 'new' goals in the streak.
      else
        break    
      end
    end
    result
  end
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  respond_to :html

  def index
    @blogs = Blog.paginate(page: params[:page], per_page: 10)
    respond_with(@blogs)
  end

  def show
    @blog = Blog.find(params[:id])
    respond_with(@blog)
  end

  def new
    @blog = Blog.new
    respond_with(@blog)
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.save
    respond_with(@blog)
  end

  def update
    @blog = Blog.find(params[:id])
    @blog.update(blog_params)
    respond_with(@blog)
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    respond_with(@blog)
  end

  private
    def blog_params
      params.require(:blog).permit(:creator, :title, :body, :date)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@blog = Blog.find(params[:blog_id])
		@comment = @blog.comments.create(comment_params)
		redirect_to blog_path(@blog)
	end

	def destroy
		@blog = Blog.find(params[:blog_id])
		@comment = @blog.comments.find(params[:id])
		@comment.destroy
		redirect_to blog_path(@blog)
	end

	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  respond_to :html
  
  def confirmation
  end
  
  def getintouch
  end
  
  def purchase
  end
  
  def index
  	
  	if user_signed_in?
  	  redirect_to profile_path(current_user)
  	end
  	@blog = Blog.all
  end
  
  def contact
  end

  def thank_you
    @name = params[:name]
    @email = params[:email]
    @message = params[:message] || "Hello!"
    # Only try to send this email on a POST
    # if request.post?
    # or make a feedback form controller and send in the create action
    
    # ActionMailer::Base.mail( FOR TEST PURPOSES
    #     :from => @email, 
  	 # 	:to => 'erikvdw@comcast.net', 
  	 # 	:subject => "A new contact form message from #{@name}", 
  	 # 	:body => @message).deliver
  	UserMailer.contact_form(@email, @name, @message).deliver
  	  	
  end

  def about
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def create #You want might to make actions more specific.
    token = params[:stripeToken] #The token when the form is posted includes the stripe token in the url.
    # Create the charge in stripes servers.  This is what commits the transaction.
    begin
      charge = Stripe::Charge.create(
        :amount => 200,
        :currency => "usd",
        :source => token,
        :description => params[:stripeEmail]
        )
      rescue Stripe::CardError => e 
        #The card was decline because of number/ccv error, expired error, bank decline, or zip error
        
        body = e.json_body
        err = body[:error]
        flash[:error] = "There was an error in processing your card: #{err[:message]}"
    end
    respond_to do |format|
      format.html { redirect_to "/purchase", notice: "Purchase was successfully completed.  We'll be in contact shortly!" }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!, except: [:show]
	#load_and_authorize_resource

	def show
		@user = User.find(params[:id])
		# TODO - figure out how to deal with current user
		@goal = Goal.new
	end
	
	def edit
	end
	def update
		@user.update_attributes(user_params)
	end	

	private
	def user_params
		require(:user)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goal_comments_helper.rb
module GoalCommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
 
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <!-- ERROR REPORTING -->
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!-- FIELDS HERE -->

  <div class="field"><!-- CREATOR -->
    <%= f.label :creator %><br>
    <%= f.text_field :creator, required: true %>
  </div>
  <div class="field" > <!-- TITLE -->
    <%= f.label :title %><br>
    <%= f.text_field :title, required: true %>
  </div>
  <div class="field text-area"> <!-- BODY -->
    <%= f.label :body %><br>
    <%= f.text_area :body, required: true %>
  </div>
  <div class="field"> <!-- DATE -->
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions"> <!-- SUBMIT BUTTON -->
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<section class="container">  
	<%= render 'form' %>

	<%= link_to 'Show', @blog %> |
	<%= link_to 'Back', blogs_path %>

</section>

app/views/blogs/index.html.erb
<h1>Blog home</h1>

<section class="container">
  <%= link_to "New Post", new_blog_path %>
  <% @blogs.each do |blog| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= link_to blog.title, blog %></h3>
      </div>
      <div class="panel-body">
        By: <%= blog.creator %>, <%= time_ago_in_words(blog.created_at) %> ago on <%= blog.created_at.strftime('%B %d %Y') %>, Last updated <%= blog.updated_at.strftime('%B %d') if blog.updated_at %>.
      </div>
      <div class="panel-body">
        <%= blog.body.first(400).humanize %>
      </div>
      <div class="panel-body">
        <%= link_to "Edit", edit_blog_path(blog) %> | <%= link_to "Delete", blog, method: :delete, data: { confirm: 'Are you sure?' } %>  
      </div>
    </div>
  <% end %>
  <%= will_paginate @blogs %>
</section>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>
<!-- SHOW THE BLOG POST -->
<div class="container">
	<h1><%= @blog.title %></h1>
	<br>
	
	<div class="panel panel-default">
	  <div class="panel-body">
	    <p><%= @blog.body %></p>
	  </div>
	  <div class="panel-footer">
	  	<p>by <%= @blog.creator %> on <%= @blog.date %>, Post number:<strong><%= @blog.id %></strong></p>
	  </div>
	</div>

	<%= link_to 'Edit', edit_blog_path(@blog) %> |
	<%= link_to 'Back', blogs_path %>
</div>
<!-- FORM FOR CREATING COMMENTS -->
<% if false %>
	<div class="container">
		<h2>Add a comment:</h2>
		<%= form_for([@blog, @blog.comments.build]) do |f| %>
			<p>
				<%= f.label :commenter %><br>
				<%= f.text_field :commenter %>
			</p>
			<p>
				<%= f.label :body %><br>
				<%= f.text_area :body %>
			</p>
			<p>
				<%= f.submit %>
			</p>
		<% end %>
	</div>
	<!-- SHOW THE COMMENTS ALREADY MADE -->
	<div class="container">
	<% @blog.comments.each do |comment| %>
		<p>
			<strong>Commenter:</strong>
			<%= comment.commenter %> says:
		</p>
		<p>
			<%= comment.body %>
		</p>
		<!-- MAKE IT POSSIBLE TO DELETE A COMMENT -->
	<%= link_to 'Delete', [comment.blog, comment],
		method: :delete,
		data: { confirm: 'Are you sure?' } %>
	<% end %>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <h1><%= @user.full_name %></h1> <!-- CHANGE TO FULL_NAME ONCE DEVISE FIELDS ARE ADDED AND CONTROLLER UPDATED -->
    </div>
    <div class="col-sm-6">
      <h1><%= @user.streak %></h1> <!-- CHANGE TO FULL_NAME ONCE DEVISE FIELDS ARE ADDED AND CONTROLLER UPDATED -->
    </div>
  </div>
  
  <% if user_signed_in? && @user == current_user %>
  <div class="row">
    <div class="col-sm-12">
      <h2>Create a new goal</h2>
      <%= form_for(@goal) do |f| %>
        <div class="form-group">
          <%= f.text_area :content, class: 'form-input input-large', rows: 2, cols: 50 %>
        </div>
        <%= f.submit "Save", class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
  <% end %>
  
  
  <% @user.goals.order(created_at: :desc).each do |goal| %>
    <%= render goal %>
  <% end %>
</div>