config/routes.rb
Rails.application.routes.draw do
  resources :payments, only: [:create]
  
  resources :charges
  
  resources :profiles, only: [:show]
  
  resources :goals do
    patch 'achieve', on: :member  #achieve_goal_path(goal)
  end

  resources :goal_comments do
    resources :likes 
  end  
  resources :blogs  
  
  
  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :registrations => "registrations" }
  
  root 'pages#getintouch'
  get '/confirmation' => 'pages#confirmation'
  
  get '/get-in-touch' => 'pages#getintouch'
  
  get 'thank-you' => 'pages#thank_you'
  post 'thank-you' => 'pages#thank_you'
  
  get 'purchase' => 'pages#purchase'
  post 'purchase' => 'payments#create'
  
  get 'about' => 'pages#about'

  get 'faq' => 'pages#faq'

  get 'contact' => 'pages#contact'
  post 'contact' => 'pages#contact'

  get 'form_input', to: 'form_example#form_input'

  post 'form_output', to: 'form_example#form_output'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)
    can :manage, User, id: user.id
    if user.is_admin?
        can :access, :rails_admin
        can :dashboard
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
	validates :creator, presence: true
	validates :creator, length: {minimum:5}
	validates :title, presence: true
	validates :title, length: {maximum:200}
	validates :body, length: {minimum:50}
	has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog
end

app/models/goal.rb
class Goal < ActiveRecord::Base
    
    belongs_to :user
    has_many :goal_comments, dependent: :destroy
    has_many :likes, as: :likeable
end

app/models/goal_comment.rb
class GoalComment < ActiveRecord::Base
    belongs_to :goal
    belongs_to :user
    
    has_many :likes, as: :likeable
end

app/models/like.rb
class Like < ActiveRecord::Base
    
   belongs_to :likeable, polymorphic: true #How to get dependent: :destroy here? 
end

app/models/streak.rb
class Streak < ActiveRecord::Base
  
  belongs_to :User, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  has_many :goals, dependent: :destroy
  has_many :goal_comments, dependent: :destroy
  # has_one :streak, dependent: :destroy  # use a streak model if you want to maintain a history of streak over times
  
  
  # This method calculates data on the fly (meaning it's not stored in the database)
  def streak
    result = 0
    goals.order(created_at: :desc).each do |goal|
      # TODO ignore new goals in the streak 
      if goal.achieved_status?
        result += 1 
      elsif result == 0
        # ignore 'new' goals in the streak.
      else
        break    
      end
    end
    result
  end
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  respond_to :html

  def index
    @blogs = Blog.paginate(page: params[:page], per_page: 10)
    respond_with(@blogs)
  end

  def show
    @blog = Blog.find(params[:id])
    respond_with(@blog)
  end

  def new
    @blog = Blog.new
    respond_with(@blog)
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.save
    respond_with(@blog)
  end

  def update
    @blog = Blog.find(params[:id])
    @blog.update(blog_params)
    respond_with(@blog)
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    respond_with(@blog)
  end

  private
    def blog_params
      params.require(:blog).permit(:creator, :title, :body, :date)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  respond_to :html
  
  def confirmation
  end
  
  def getintouch
  end
  
  def purchase
  end
  
  def index
  	
  	if user_signed_in?
  	  redirect_to profile_path(current_user)
  	end
  	@blog = Blog.all
  end
  
  def contact
  end

  def thank_you
    @name = params[:name]
    @email = params[:email]
    @message = params[:message] || "Hello!"
    # Only try to send this email on a POST
    # if request.post?
    # or make a feedback form controller and send in the create action
    
    # ActionMailer::Base.mail( FOR TEST PURPOSES
    #     :from => @email, 
  	 # 	:to => 'erikvdw@comcast.net', 
  	 # 	:subject => "A new contact form message from #{@name}", 
  	 # 	:body => @message).deliver
  	UserMailer.contact_form(@email, @name, @message).deliver
  	  	
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!, except: [:show]
	#load_and_authorize_resource

	def show
		@user = User.find(params[:id])
		# TODO - figure out how to deal with current user
		@goal = Goal.new
	end
	
	def edit
	end
	def update
		@user.update_attributes(user_params)
	end	

	private
	def user_params
		require(:user)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
 
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<!--FOOTER-->
    <hr>
	<footer class="container">
      <ul class="list-inline">
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Contact!', contact_path %></li>
        <li><%= link_to 'FAQ', faq_path %></li>
      </ul> 
      <p><span class="glyphicon glyphicon-copyright-mark"></span> PeerAchieve 2013</p>
    </footer>
    <%# cl_image_tag("sample.jpg", width: 100, height: 150, crop: :fill) %>   

    <!--JAVASCRIPT-->
    <!-- Including rails js -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <!-- For stellar.js -->
    <script type="text/javascript">$(function(){ $(window).stellar(); });</script><!--Does need to be called on window-->
    
    <!--Script for smooth scrolling to DESCRIPTION and TEAM sections-->
    <script type="text/javascript">
      var $root = $('html, body');
        $('.navbar-nav a').click(function() {
            var href = $.attr(this, 'href');
            $root.animate({
                scrollTop: $(href).offset().top
            }, 500, function () {
                window.location.hash = href;
            });
            return false;
        });
    </script>

    <!--Google Analytics implementation-->
    <script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-57104689-1', 'auto');
      ga('send', 'pageview');
    </script>
</body>
</html>

app/views/layouts/application.html.erb
<%= render '/layouts/header' %>



<% flash.each do |key, value| %>
  <% if key == 'alert' %>
    <div class="alert alert-danger"><%= value %></div>
  <% elsif key == 'notice' %>
    <div class="alert alert-success"><%= value %></div>
  <% end %>
<% end %>

<%= yield %>

<%= render '/layouts/footer' %>
	

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
  <head>

    <!--Info -->
    <title><%= "Error :: #{@app_name}" %></title>

    <!--Styling -->
    <style>
      
		html {
			height: 100%;
			background: #fff asset_url("custom_error_pages/bg.png") bottom repeat-x;
		}
		
		body {
			font-family: Helvetica, Arial, Sans-Serif;
			font-size: 14px;
		}
		.error_container {
			display: block;
			margin: auto;
			margin: 10% auto 0 auto;
			width: 30%;
		}
		
		.error_container .error {
			display: block;
			text-align: center;
		}
		
		.error_container .error img.alert {
			display: block;
			margin: 0 auto 25px auto;
		}
		
		.error_container .message > * {
			display: block;
		}
		
		.error_container .message strong {
			font-weight: bold;
			font-size: 1.5em;
			color: #f00;
			margin: 15px 0 0;
		}

		.error_container .message span {
			margin: 5px auto 0;
			font-size: 0.75em;
			color: #606060;
		}
		
		.error_container .contact {
			display: block;
			text-align: center;
			margin: 20px 0 0 0;
		}
		
		.error_container .contact a {
			display: inline-block;
			margin: 0 -1px; /* For inline block & ERB - HAML removes whitespace; ERB does now - http://haml.info/docs/yardoc/file.REFERENCE.html#whitespace_removal__and_ */
			opacity: 0.4;
			transition: opacity 0.15s ease;
		}

		.error_container .contact a img {
			display: block;
			width: 38px;
			height: 38px;
		}
		
		.error_container .contact a:hover {
			opacity: 0.8;
		}

    </style>
  </head>
  
  <!--Body -->
  <body>
    <div class="error_container">
      <%= yield %>
    </div>
  </body>

</html>

app/views/pages/_most_recent_articles_body.html.erb
<% i=1 %>
<ol>
	<% @blog.each do |blog| %> 
		<li><%= link_to blog.title, blog_path(i), method: :get if i<4 %></li>
		<% i+=1 %>
	<% end %>
</ol>

app/views/pages/_most_recent_articles_header.html.erb
Most Recent Blog Articles

app/views/pages/about.html.erb
<div class="jumbotron background-image-6" style="height:1000px">
    <div class="container">
        <h1>About</h1>
        <div class="col-md-4 col-sm-12">
          <h3>Our Service</h3>
          <p>We use our access to peer-reviewed science on motivation, planning, goal-oriented behaivor, habit formation, and behaivoral extinction to give the best possible advice on how to achieve your goals.  We keep tabs on your daily progress and are always available within 24 hours for any questions you might have.</p>
        </div>
        
        <div class="col-md-4 col-sm-12">
          <h3>Story</h3>
          <p>Our founder struggled with motivation, poor habits and failure to achieve his goals.  He started researching why this might be through his university library, and found that there are mostly uniform reasons why motivation flags, why habits are hard to change and why goals don't get achieved.  He wants to share that information so everyone can achieve their goals.</p>
        </div>
        
        <div class="col-md-4 col-sm-12">
          <h3>Mission</h3>
          <p>Our mission is to help people achieve their goals effectively and with such a confidence in our product that we can guarantee its benefits.  We seek to create a more successful and goal-oriented world.</p>
        </div>
    </div>
</div>

app/views/pages/confirmation.html.erb
<div class="container-fluid background-image-4">
  <div class="row" style="height:200px;"></div>
  <div class="row jumbotron" style="background-color: rgba(0, 0, 0, 0.5);">
    <div class="col-md-12" style="height:150px;">
        <h2 class="white text-center">Thank you.</h2>
        <p class="white text-center">We have recieved your payment and look forward to working with you.</p>
    </div>
  </div>
  <div class="row" style="height:400px;"></div>
</div>

app/views/pages/contact.html.erb
<main class="container contact">
  <h1>Contact</h1>
  <%= flash[:notice] %>
  <p class="lead">Call me personally, or drop a quick email about any questions or comments you have!</p>
  
  <%= form_tag("/thank-you") do %>
      <div class="row">
        <div class="col-md-2">
          <div class="input-group">
              <%= text_field_tag :name, nil, class: 'form-control', placeholder: 'Name' %>
          </div>
        </div>
        <div class="col-md-4">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">@</span>
            <%= text_field_tag :email, nil, class: 'form-control', placeholder: 'Email' %>
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-6">
          <div class="input-group text-area-wide">
              <%= text_area_tag :message, nil, class: 'form-control text-area-wide', placeholder: 'Message' %>
          </div>
        </div>
      </div>
      <br>
      <%= submit_tag 'Send Message', class: 'btn btn-success' %>
  <% end %>
  
</main>

app/views/pages/faq.html.erb
<div class="jumbotron background-image-5" style="height:1000px">
  <div class="container white">
    <div class="row">
      <div class="col-md-8 for-background">
        <div class="row">
          <div class="col-md-12">
            <h1 class="text-center">Frequently Asked Questions</h1>
            <p class="lead text-center">If you still have questions, please <a href="contact.html">contact us!</a></p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-10 col-md-offset-1">
            <h3><u>Guarantee</u></h3>
            <p>If, for any reason you are not satisfied at the end of the month, just use the <%= link_to 'Contact Us', contact_path %> page and you will recieve a refund in 6-11 days (depending on your bank).  We take a satisfaction inventory every week to make sure you're getting what you want, and always enjoy your feedback.</p>
            <h3><u>Quality</u></h3>
            <p>Our service pays above industry wages to attract top-tier talent.  Every one of our employees recieves incentive pay based on your satisfaction.</p>
            <h3><u>Is it worth it?</u></h3>
            <p>The honest answer depends on how valuable your goals are to you.  Really consider if achieving your goal is worth that much to you.  If you have a goal that is worth less to you than $800, you might consider finding a goal worth more to you to focus on.  We guarantee our results because we believe in our service.</p>
            <br>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/getintouch.html.erb
<div class="container">
    <br>
    <h1>Achieve Your Goals.</h1>
    <br>
</div>
<div class="jumbotron background-image-1">
    <div class="container">
        <div class="row">
            <div class="col-md-8 white">
                <h1>Purchase Consulting</h1>
                <p class="lead" >Be connected with an expert, intelligent, helpful and friendly consultant who cares about your achievement.</p>
                <h3>Our Guarantee</h3>
                <p class="lead" >If you aren't satisfied with our service for any reason, <span style="color:#52A552">we will refund your money, no questions asked.</span></p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 col-md-offset-2 white">
                <p>Be more productive</p>
                <p>Balance your time</p>
                <p>Secure your finances</p>
                <p>Lose weight</p>
            </div>
            <div class="col-md-3 white">
                <p>Win a new job</p>
                <p>Work better with others</p>
                <p>Establish a healthy lifestyle</p>
                <p>Create change</p>
            </div>
        </div>
       <div class="row">
         <div class="col-md-8">
            <h3>Schedule a Session</h3>
           <p class="lead"><%= link_to '$800/mo', faq_path, {style: 'color:#52A552;'} %>-You don't pay until after your first meeting.</p>
         </div>
       </div>
        <div class="row">
          <div class="col-md-6"><%= form_tag("/pages/thank_you") do %>
              <div class="row">
                <div class="col-md-4">
                  <div class="input-group">
                      <%= text_field_tag :name, nil, class: 'form-control', placeholder: 'Name' %>
                  </div>
                </div>
                <div class="col-md-8">
                  <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">@</span>
                    <%= text_field_tag :email, nil, class: 'form-control', placeholder: 'Email' %>
                  </div>
                </div>
              </div>
              <br>
              <div class="row">
                <div class="col-md-12">
                  <div class="input-group text-area-wide">
                    <%= text_area_tag :message, nil, class: 'form-control text-area-wide', placeholder: 'What do you want to achieve?' %>
                  </div>
                </div>
              </div>
              <br>
              <%= submit_tag 'Send Message', class: 'btn btn-success' %>
            <% end %></div>
        </div>
        <div class="row">
          <div class="col-md-8 white">
              <h4>Not sure?</h4>
              <p>No problem.  Just send a quick email and we'll get back to you within 24 hours.</p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <%= form_tag("/pages/thank_you") do %>
              <div class="row">
                <div class="col-md-4">
                  <div class="input-group">
                      <%= text_field_tag :name, nil, class: 'form-control', placeholder: 'Name' %>
                  </div>
                </div>
                <div class="col-md-8">
                  <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">@</span>
                    <%= text_field_tag :email, nil, class: 'form-control', placeholder: 'Email' %>
                  </div>
                </div>
              </div>
              <br>
              <div class="row">
                <div class="col-md-12">
                  <div class="input-group text-area-wide">
                    <%= text_area_tag :message, nil, class: 'form-control text-area-wide', placeholder: "You'll get a response within 24 hours.  Ask anything." %>
                  </div>
                </div>
              </div>
              <br>
              <%= submit_tag 'Send Message', class: 'btn btn-success' %>
            <% end %>
          </div>
        </div>
    </div>
</div>

app/views/pages/purchase.html.erb
<script src="//js.stripe.com/v2/"></script>
<script>
    (function() {
        Stripe.setPublishableKey('pk_test_UQ2EqhNNQRrDkD5V0Z1xgpS5');
    })();
</script>
<script>
    $('#payment-form').on('submit', generateToken);
 
    var generateToken = function(e) {
        var form = $(this);
     
        // No pressing the buy now button more than once
        form.find('button').prop('disabled', true);
     
        // Create the token, based on the form object
        Stripe.create(form, stripeResponseHandler);
     
        // Prevent the form from submitting
        e.preventDefault();
    };
     
    var stripeResponseHandler = function(status, response) {};
</script>


<div class="jumbotron background-image-3">
  <div class="container" style="height: 650px">
    <div class="row" style="min-height:180px;"></div>
    <div class="row">
        <div class="col-md-offset-1 col-md-10">
          <h2 class="white text-center" style="text-shadow: -4px 2px 2px rgba(150, 150, 150, 1);">We can't wait to help you achieve your goals.</h2>
          <br>
        </div>
    </div>
    <div class="row">
      <div class="center-div">
        <%= form_tag "/payments" do %>
          <%= render partial: "shared/stripe_checkout_button" %>
        <% end %>
      </div>
    </div>
  </div>
    <div class="row">
      <div class="col-md-6">
        
        <p class="white">Site encrypted using Heroku SSLEndpoints, Stripe JS and <a style="color:white;" target="_blank" href="https://www.expeditedssl.com/simple-ssl-scanner/scan?target_domain=www.achievemore.co">Expedited SSL</a>.</p>
      </div>
    </div>
  </div>
</div>
        

app/views/pages/thank_you.html.erb
<div class="jumbotron background-image-2">
    <div class="container">
        <div class="row">
            <div class="col-md-12" style="min-height:800px;">
                <p class="white text-center vertical-align" style="height:400px;line-height:400px">Thank you.  We have recieved your message and will respond within 24 hours.</p>
            </div>
        </div>
    </div>
</div>

app/views/shared/_stripe_checkout_button.html.erb
<script
  src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-image="/assets/square-image.png"
  data-name="Achieve More"
  data-description="1 Month ($800)"
  data-amount="2000">
</script>